// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: pkg/filter/validator/testdata/contact.proto

package testdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metadata represents email metadata for three-level nesting tests
type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Priority      int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_pkg_filter_validator_testdata_contact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_filter_validator_testdata_contact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_pkg_filter_validator_testdata_contact_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Metadata) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// Email represents an email address for nested field testing
type Email struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Verified      bool                   `protobuf:"varint,2,opt,name=verified,proto3" json:"verified,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Email) Reset() {
	*x = Email{}
	mi := &file_pkg_filter_validator_testdata_contact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_filter_validator_testdata_contact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_pkg_filter_validator_testdata_contact_proto_rawDescGZIP(), []int{1}
}

func (x *Email) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Email) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *Email) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Email) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Address represents a physical address for deep nesting tests
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_pkg_filter_validator_testdata_contact_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_filter_validator_testdata_contact_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_pkg_filter_validator_testdata_contact_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

// Profile represents nested settings for deep nesting tests
type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Theme         string                 `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	Notifications bool                   `protobuf:"varint,2,opt,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_pkg_filter_validator_testdata_contact_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_filter_validator_testdata_contact_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_pkg_filter_validator_testdata_contact_proto_rawDescGZIP(), []int{3}
}

func (x *Profile) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *Profile) GetNotifications() bool {
	if x != nil {
		return x.Notifications
	}
	return false
}

// Contact represents a contact with nested messages for traversal testing
type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         *Email                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Address       *Address               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Profile       *Profile               `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	PhoneNumbers  []string               `protobuf:"bytes,5,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_pkg_filter_validator_testdata_contact_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_filter_validator_testdata_contact_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_pkg_filter_validator_testdata_contact_proto_rawDescGZIP(), []int{4}
}

func (x *Contact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contact) GetEmail() *Email {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *Contact) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Contact) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *Contact) GetPhoneNumbers() []string {
	if x != nil {
		return x.PhoneNumbers
	}
	return nil
}

var File_pkg_filter_validator_testdata_contact_proto protoreflect.FileDescriptor

const file_pkg_filter_validator_testdata_contact_proto_rawDesc = "" +
	"\n" +
	"+pkg/filter/validator/testdata/contact.proto\x12\btestdata\">\n" +
	"\bMetadata\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\"\x85\x01\n" +
	"\x05Email\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1a\n" +
	"\bverified\x18\x02 \x01(\bR\bverified\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12.\n" +
	"\bmetadata\x18\x04 \x01(\v2\x12.testdata.MetadataR\bmetadata\"O\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\"E\n" +
	"\aProfile\x12\x14\n" +
	"\x05theme\x18\x01 \x01(\tR\x05theme\x12$\n" +
	"\rnotifications\x18\x02 \x01(\bR\rnotifications\"\xc3\x01\n" +
	"\aContact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x05email\x18\x02 \x01(\v2\x0f.testdata.EmailR\x05email\x12+\n" +
	"\aaddress\x18\x03 \x01(\v2\x11.testdata.AddressR\aaddress\x12+\n" +
	"\aprofile\x18\x04 \x01(\v2\x11.testdata.ProfileR\aprofile\x12#\n" +
	"\rphone_numbers\x18\x05 \x03(\tR\fphoneNumbersB;Z9github.com/zshainsky/aip160/pkg/filter/validator/testdatab\x06proto3"

var (
	file_pkg_filter_validator_testdata_contact_proto_rawDescOnce sync.Once
	file_pkg_filter_validator_testdata_contact_proto_rawDescData []byte
)

func file_pkg_filter_validator_testdata_contact_proto_rawDescGZIP() []byte {
	file_pkg_filter_validator_testdata_contact_proto_rawDescOnce.Do(func() {
		file_pkg_filter_validator_testdata_contact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_filter_validator_testdata_contact_proto_rawDesc), len(file_pkg_filter_validator_testdata_contact_proto_rawDesc)))
	})
	return file_pkg_filter_validator_testdata_contact_proto_rawDescData
}

var file_pkg_filter_validator_testdata_contact_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_filter_validator_testdata_contact_proto_goTypes = []any{
	(*Metadata)(nil), // 0: testdata.Metadata
	(*Email)(nil),    // 1: testdata.Email
	(*Address)(nil),  // 2: testdata.Address
	(*Profile)(nil),  // 3: testdata.Profile
	(*Contact)(nil),  // 4: testdata.Contact
}
var file_pkg_filter_validator_testdata_contact_proto_depIdxs = []int32{
	0, // 0: testdata.Email.metadata:type_name -> testdata.Metadata
	1, // 1: testdata.Contact.email:type_name -> testdata.Email
	2, // 2: testdata.Contact.address:type_name -> testdata.Address
	3, // 3: testdata.Contact.profile:type_name -> testdata.Profile
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_filter_validator_testdata_contact_proto_init() }
func file_pkg_filter_validator_testdata_contact_proto_init() {
	if File_pkg_filter_validator_testdata_contact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_filter_validator_testdata_contact_proto_rawDesc), len(file_pkg_filter_validator_testdata_contact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_filter_validator_testdata_contact_proto_goTypes,
		DependencyIndexes: file_pkg_filter_validator_testdata_contact_proto_depIdxs,
		MessageInfos:      file_pkg_filter_validator_testdata_contact_proto_msgTypes,
	}.Build()
	File_pkg_filter_validator_testdata_contact_proto = out.File
	file_pkg_filter_validator_testdata_contact_proto_goTypes = nil
	file_pkg_filter_validator_testdata_contact_proto_depIdxs = nil
}
