// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: pkg/filter/validator/testdata/person.proto

package testdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status represents a user status for enum validation testing
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_INACTIVE    Status = 2
	Status_STATUS_PENDING     Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_INACTIVE",
		3: "STATUS_PENDING",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
		"STATUS_INACTIVE":    2,
		"STATUS_PENDING":     3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_filter_validator_testdata_person_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_pkg_filter_validator_testdata_person_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_filter_validator_testdata_person_proto_rawDescGZIP(), []int{0}
}

// Person represents a person with an enum field for enum validation testing
type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=testdata.Status" json:"status,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Verified      bool                   `protobuf:"varint,4,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_pkg_filter_validator_testdata_person_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_filter_validator_testdata_person_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_pkg_filter_validator_testdata_person_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Person) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Person) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

var File_pkg_filter_validator_testdata_person_proto protoreflect.FileDescriptor

const file_pkg_filter_validator_testdata_person_proto_rawDesc = "" +
	"\n" +
	"*pkg/filter/validator/testdata/person.proto\x12\btestdata\"t\n" +
	"\x06Person\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.testdata.StatusR\x06status\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12\x1a\n" +
	"\bverified\x18\x04 \x01(\bR\bverified*\\\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x13\n" +
	"\x0fSTATUS_INACTIVE\x10\x02\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x03B;Z9github.com/zshainsky/aip160/pkg/filter/validator/testdatab\x06proto3"

var (
	file_pkg_filter_validator_testdata_person_proto_rawDescOnce sync.Once
	file_pkg_filter_validator_testdata_person_proto_rawDescData []byte
)

func file_pkg_filter_validator_testdata_person_proto_rawDescGZIP() []byte {
	file_pkg_filter_validator_testdata_person_proto_rawDescOnce.Do(func() {
		file_pkg_filter_validator_testdata_person_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_filter_validator_testdata_person_proto_rawDesc), len(file_pkg_filter_validator_testdata_person_proto_rawDesc)))
	})
	return file_pkg_filter_validator_testdata_person_proto_rawDescData
}

var file_pkg_filter_validator_testdata_person_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_filter_validator_testdata_person_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_filter_validator_testdata_person_proto_goTypes = []any{
	(Status)(0),    // 0: testdata.Status
	(*Person)(nil), // 1: testdata.Person
}
var file_pkg_filter_validator_testdata_person_proto_depIdxs = []int32{
	0, // 0: testdata.Person.status:type_name -> testdata.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_filter_validator_testdata_person_proto_init() }
func file_pkg_filter_validator_testdata_person_proto_init() {
	if File_pkg_filter_validator_testdata_person_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_filter_validator_testdata_person_proto_rawDesc), len(file_pkg_filter_validator_testdata_person_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_filter_validator_testdata_person_proto_goTypes,
		DependencyIndexes: file_pkg_filter_validator_testdata_person_proto_depIdxs,
		EnumInfos:         file_pkg_filter_validator_testdata_person_proto_enumTypes,
		MessageInfos:      file_pkg_filter_validator_testdata_person_proto_msgTypes,
	}.Build()
	File_pkg_filter_validator_testdata_person_proto = out.File
	file_pkg_filter_validator_testdata_person_proto_goTypes = nil
	file_pkg_filter_validator_testdata_person_proto_depIdxs = nil
}
