package module2ast
// Package ast defines the Abstract Syntax Tree nodes for AIP-160 filter expressions.

















































































































































































































































}	return fmt.Sprintf("%s(%s)", f.Function, strings.Join(args, ", "))	}		args = append(args, arg.String())	for _, arg := range f.Arguments {	var args []string	// TODO: Build argument list and return formatted stringfunc (f *FunctionCall) String() string {// Then join them with ", " using strings.Join()// You'll need to loop through Arguments and call String() on each// Hint: Format should be "<function>(<arg1>, <arg2>, ...)"// TODO: Implement String() methodfunc (f *FunctionCall) TokenLiteral() string { return f.Token.Literal }func (f *FunctionCall) expressionNode()      {}}	Arguments []Expression // List of argument expressions	Function  string       // Function name	Token     lexer.Token  // The IDENTIFIER token (function name)type FunctionCall struct {// Examples: timestamp(created_at), duration(start, end)// FunctionCall represents a function call expression.}	return fmt.Sprintf("%s:%s", h.Collection.String(), h.Member.String())	// TODO: Return formatted string with colon separatorfunc (h *HasExpression) String() string {// Hint: Format should be "<collection>:<member>" - NO parentheses// TODO: Implement String() methodfunc (h *HasExpression) TokenLiteral() string { return h.Token.Literal }func (h *HasExpression) expressionNode()      {}}	Member     Expression  // The member to check for	Collection Expression  // The collection field	Token      lexer.Token // The HAS (:) tokentype HasExpression struct {// Examples: tags:urgent, labels:"bug", roles:admin// HasExpression represents the has operator for checking collection membership.}	return fmt.Sprintf("%s.%s", t.Left.String(), t.Right.String())	// TODO: Return formatted string with dot separatorfunc (t *TraversalExpression) String() string {// Hint: Format should be "<left>.<right>" - NO parentheses for this one!// TODO: Implement String() methodfunc (t *TraversalExpression) TokenLiteral() string { return t.Token.Literal }func (t *TraversalExpression) expressionNode()      {}}	Right Expression  // Right side (an identifier)	Left  Expression  // Left side (an identifier or another traversal)	Token lexer.Token // The DOT tokentype TraversalExpression struct {// Examples: user.name, address.city, author.email// TraversalExpression represents field traversal with the dot operator.}	return fmt.Sprintf("(%s%s)", u.Operator, u.Right.String())	}		return fmt.Sprintf("(%s %s)", u.Operator, u.Right.String())	if u.Operator == "NOT" {	// TODO: Return formatted string with parenthesesfunc (u *UnaryExpression) String() string {// Hint: Format should be "(<operator><right>)" - no space between operator and right// TODO: Implement String() methodfunc (u *UnaryExpression) TokenLiteral() string { return u.Token.Literal }func (u *UnaryExpression) expressionNode()      {}}	Right    Expression  // The expression being operated on	Operator string      // The unary operator	Token    lexer.Token // The operator token (NOT, MINUS)type UnaryExpression struct {// Examples: NOT status = "inactive", -age// UnaryExpression represents a unary operation (currently just NOT or negation).}	return fmt.Sprintf("(%s %s %s)", l.Left.String(), l.Operator, l.Right.String())	// TODO: Return formatted string with parenthesesfunc (l *LogicalExpression) String() string {// Hint: Same format as ComparisonExpression: "(<left> <operator> <right>)"// TODO: Implement String() methodfunc (l *LogicalExpression) TokenLiteral() string { return l.Token.Literal }func (l *LogicalExpression) expressionNode()      {}}	Right    Expression  // Right side of the logical operation	Operator string      // The logical operator ("AND" or "OR")	Left     Expression  // Left side of the logical operation	Token    lexer.Token // The operator token (AND, OR)type LogicalExpression struct {// Examples: age > 18 AND status = "active", role = "admin" OR role = "owner"// LogicalExpression represents a logical operation between two expressions.}	return fmt.Sprintf("(%s %s %s)", c.Left.String(), c.Operator, c.Right.String())	// TODO: Return formatted string with parenthesesfunc (c *ComparisonExpression) String() string {// Remember to call .String() on Left and Right!// Hint: Format should be "(<left> <operator> <right>)"// TODO: Implement String() methodfunc (c *ComparisonExpression) TokenLiteral() string { return c.Token.Literal }func (c *ComparisonExpression) expressionNode()      {}}	Right    Expression  // Right side of the comparison	Operator string      // The comparison operator as a string	Left     Expression  // Left side of the comparison	Token    lexer.Token // The operator token (=, !=, <, >, <=, >=)type ComparisonExpression struct {// Examples: age > 18, name = "John", status != "inactive"// ComparisonExpression represents a comparison between two expressions.}	return "null"func (n *NullLiteral) String() string {// Hint: Just return "null"// TODO: Implement String() methodfunc (n *NullLiteral) TokenLiteral() string { return n.Token.Literal }func (n *NullLiteral) expressionNode()      {}}	Token lexer.Token // The NULL tokentype NullLiteral struct {// NullLiteral represents a null value.}	return "false"	}		return "true"	if b.Value {func (b *BooleanLiteral) String() string {// Hint: Return "true" or "false" based on the Value field// TODO: Implement String() methodfunc (b *BooleanLiteral) TokenLiteral() string { return b.Token.Literal }func (b *BooleanLiteral) expressionNode()      {}}	Value bool        // The boolean value	Token lexer.Token // The TRUE or FALSE tokentype BooleanLiteral struct {// Examples: true, false// BooleanLiteral represents a boolean value.}	return fmt.Sprintf("%g", n.Value)	// TODO: Return the number as a formatted stringfunc (n *NumberLiteral) String() string {// Hint: Use fmt.Sprintf() with %g format specifier// TODO: Implement String() methodfunc (n *NumberLiteral) TokenLiteral() string { return n.Token.Literal }func (n *NumberLiteral) expressionNode()      {}}	Value float64     // The parsed numeric value	Token lexer.Token // The NUMBER tokentype NumberLiteral struct {// Examples: 42, 3.14, 2.5e10// NumberLiteral represents a numeric value (integer or float).func (s *StringLiteral) String() string       { return "\"" + s.Value + "\"" }func (s *StringLiteral) TokenLiteral() string { return s.Token.Literal }func (s *StringLiteral) expressionNode()      {}}	Value string      // The string value (without quotes)	Token lexer.Token // The STRING tokentype StringLiteral struct {// Examples: "John", 'active'// StringLiteral represents a string value in quotes.func (i *Identifier) String() string       { return i.Value }func (i *Identifier) TokenLiteral() string { return i.Token.Literal }func (i *Identifier) expressionNode()      {}}	Value string      // The actual identifier name	Token lexer.Token // The IDENTIFIER tokentype Identifier struct {// Examples: name, age, user, email// Identifier represents a field name in a filter expression.}	return ""	}		return p.Expression.String()	if p.Expression != nil {func (p *Program) String() string {}	return ""	}		return p.Expression.TokenLiteral()	if p.Expression != nil {func (p *Program) TokenLiteral() string {}	Expression Expressiontype Program struct {// For AIP-160 filters, a program contains a single filter expression.// Program is the root node of the AST.}	expressionNode() // marker method to distinguish expressions from other node types	Nodetype Expression interface {// All filter components (comparisons, literals, identifiers, etc.) are expressions.// Expression represents any node that can be evaluated to produce a value.}	String() string	// String returns a string representation of the node (for debugging/testing).	TokenLiteral() string	// Useful for debugging and error messages.	// TokenLiteral returns the literal value of the token this node is associated with.type Node interface {// It provides common functionality for all nodes in the tree.// Node is the base interface that all AST nodes must implement.)	"github.com/zshainsky/aip160/pkg/filter/lexer"	"strings"	"fmt"import (package ast// Each node implements the Node interface and represents a specific element of the filter.// The AST represents the parsed structure of a filter expression as a tree of nodes.//