package validator

import (
	"reflect"
	"testing"
)

// Test enum type for testing purposes
type TestStatus int32

const (
	TestStatus_UNSPECIFIED TestStatus = 0
	TestStatus_ACTIVE      TestStatus = 1
	TestStatus_INACTIVE    TestStatus = 2
	TestStatus_PENDING     TestStatus = 3
)

// Companion maps (as generated by protoc)
var (
	TestStatus_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ACTIVE",
		2: "INACTIVE",
		3: "PENDING",
	}
	TestStatus_value = map[string]int32{
		"UNSPECIFIED": 0,
		"ACTIVE":      1,
		"INACTIVE":    2,
		"PENDING":     3,
	}
)

// Test struct with enum field
type TestEntityWithEnum struct {
	Status TestStatus `protobuf:"varint,1,opt,name=status,proto3,enum=validator.TestStatus" json:"status"`
	Name   string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
}

// Phase 1: Infrastructure Tests (TDD RED → GREEN)

// Test 1: EnumInfo struct creation
func TestEnumInfo_Creation(t *testing.T) {
	// RED: This test will fail until we create the EnumInfo struct
	enumInfo := &EnumInfo{
		TypeName: "TestStatus",
		ValueMap: map[string]int32{
			"ACTIVE":   1,
			"INACTIVE": 2,
		},
	}

	if enumInfo.TypeName != "TestStatus" {
		t.Errorf("Expected TypeName 'TestStatus', got '%s'", enumInfo.TypeName)
	}

	if len(enumInfo.ValueMap) != 2 {
		t.Errorf("Expected 2 values in ValueMap, got %d", len(enumInfo.ValueMap))
	}

	if enumInfo.ValueMap["ACTIVE"] != 1 {
		t.Errorf("Expected ACTIVE=1, got %d", enumInfo.ValueMap["ACTIVE"])
	}
}

// Test 2: detectEnum returns nil for non-enum field
func TestDetectEnum_NonEnumField(t *testing.T) {
	// RED: This test will fail until we implement detectEnum()
	structType := reflect.TypeOf(TestEntityWithEnum{})
	nameField, _ := structType.FieldByName("Name") // Name is not an enum

	enumInfo, isEnum := detectEnum(nameField, nameField.Type)

	if isEnum {
		t.Error("Expected isEnum=false for non-enum field 'Name'")
	}

	if enumInfo != nil {
		t.Error("Expected nil EnumInfo for non-enum field")
	}
}

// Test 3: detectEnum returns nil when protobuf tag has no enum parameter
func TestDetectEnum_NoEnumTag(t *testing.T) {
	// RED: This test validates that fields without enum= parameter are not treated as enums
	type SimpleStruct struct {
		Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count"` // No enum=
	}

	structType := reflect.TypeOf(SimpleStruct{})
	countField, _ := structType.FieldByName("Count")

	enumInfo, isEnum := detectEnum(countField, countField.Type)

	if isEnum {
		t.Error("Expected isEnum=false for field without enum= tag")
	}

	if enumInfo != nil {
		t.Error("Expected nil EnumInfo for field without enum= tag")
	}
}

// Test 4: detectEnum detects enum from protobuf tag
func TestDetectEnum_WithProtobufTag(t *testing.T) {
	// RED: This test will pass once we implement full detection logic
	structType := reflect.TypeOf(TestEntityWithEnum{})
	statusField, _ := structType.FieldByName("Status")

	enumInfo, isEnum := detectEnum(statusField, statusField.Type)

	if !isEnum {
		t.Error("Expected isEnum=true for enum field 'Status'")
	}

	if enumInfo == nil {
		t.Fatal("Expected non-nil EnumInfo for enum field")
	}

	// Verify TypeName was extracted
	if enumInfo.TypeName == "" {
		t.Error("Expected non-empty TypeName")
	}

	// Note: ValueMap might be nil if companion maps can't be found
	// That's OK - we'll handle gracefully
}

// Test 5: detectEnum with missing companion maps (graceful degradation)
func TestDetectEnum_MissingCompanionMaps(t *testing.T) {
	// RED: Test that we handle missing companion maps gracefully
	type StructWithUnknownEnum struct {
		// This enum type doesn't have companion maps defined
		Mystery int32 `protobuf:"varint,1,opt,name=mystery,proto3,enum=unknown.MysteryEnum" json:"mystery"`
	}

	structType := reflect.TypeOf(StructWithUnknownEnum{})
	mysteryField, _ := structType.FieldByName("Mystery")

	enumInfo, isEnum := detectEnum(mysteryField, mysteryField.Type)

	// Should still detect as enum from tag
	if !isEnum {
		t.Error("Expected isEnum=true even without companion maps")
	}

	if enumInfo == nil {
		t.Fatal("Expected non-nil EnumInfo even without companion maps")
	}

	// ValueMap should be empty/nil when companion maps not found
	if enumInfo.ValueMap != nil && len(enumInfo.ValueMap) > 0 {
		t.Error("Expected empty/nil ValueMap when companion maps not found")
	}
}
